name: Deploy Allure Report (Nightly)

on:
  workflow_run:
    workflows: ["Nightly Regression Tests"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Download nightly results artifact
        uses: actions/download-artifact@v4
        with:
          name: nightly-results
          path: nightly-results

      - name: Extract report
        run: |
          ls -R nightly-results
          rm -rf ./allure-report
          cp -r nightly-results/allure-report ./allure-report

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report

